/**
 * Service worker registration — bridges `vite-plugin-pwa`'s virtual module
 * into our Zustand `networkStore`. Idempotent: safe to call multiple times.
 *
 * The SW is auto-generated by Workbox via the plugin (see `vite.config.ts`).
 * In dev we enable it via `devOptions.enabled = true` to verify behavior;
 * in production it caches the app shell so the app loads offline.
 */

import { registerSW as registerSWImpl } from "virtual:pwa-register";
import { useNetworkStore } from "@/store/networkStore";

let registered = false;

export function registerServiceWorker(): void {
  if (registered) return;
  registered = true;
  const updateSW = registerSWImpl({
    immediate: true,
    onRegisterError(err) {
      console.error("[pwa] SW registration failed", err);
    },
    onOfflineReady() {
      useNetworkStore.getState().setOfflineReady(true);
    },
    onNeedRefresh() {
      useNetworkStore
        .getState()
        .setNeedRefresh(true, () => updateSW(true));
    },
  });
}
